# Copyright (c) 2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

qualTableDefinitions:
  - label: qualCoreCSVStatus
    description: >-
      Status of each event log passed to the qualification tool
    fileName: status.csv
    scope: global
    columns:
      - name: Event Log
        dataType: String
        description: >-
          Event Log Path(local/remote)
      - name: Status
        dataType: String
        description: >-
          Status whether the event log processed successfully or not
      - name: App ID
        dataType: String
        description: >-
          ID of the app associated with the event log
      - name: Description
        dataType: String
        description: >-
          Total processing time of the event log
  - label: qualCoreCSVSummary
    description: >-
      Summary of each event log processed by the qualification tool
    fileName: apps_summary.csv
    scope: global
    columns:
      - name: App Name
        dataType: String
        description: >-
          Name of application associated with the event log
      - name: App ID
        dataType: String
        description: >-
          ID of the app associated with the event log
      - name: Attempt ID
        dataType: String
        description: >-
          Attempt ID of the app associated with the event log
      - name: App Duration
        dataType: String
        description: >-
          Total runtime of the app
      - name: Executor CPU Time Percent
        dataType: float
        description: >-
          Total CPU time consumed by executors in percentage
      - name: SQL Ids with Failures
        dataType: String
        description: >-
          SQL Ids with failures
      - name: Unsupported Read File Formats and Types
        dataType: String
        description: >-
          Formats and types of files that are not supported for reading
      - name: Unsupported Write Data Format
        dataType: String
        description: >-
          Format of the data that is not supported for writing
      - name: Complex Types
        dataType: String
        description: >-
          Types of data types that are not supported for writing
      - name: Nested Complex Types
        dataType: String
        description: >-
          Types of data types that are not supported for writing
      - name: Potential Problems
        dataType: String
        description: >-
          Potential problems with the app
      - name: Longest SQL Duration
        dataType: Long
        description: >-
          The longest SQL duration in the app
      - name: SQL Stage Durations Sum
        dataType: Long
        description: >-
          The total wallClockDuration of all the stages in the app. The wallClockDuration is calculated as
          (submissionTime - completionTime) of the given stage
      - name: App Duration Estimated
        dataType: Boolean
        description: >-
          Whether the app duration is estimated or not(true/false)
      - name: Total Core Seconds
        dataType: Long
        description: >-
          The total core seconds of the app
  # the following table seems to be useless
  - label: perSqlCSVReport
    description: >-
      Report containing the details of each SQL in the app
    fileName: persql.csv
    scope: per-app
    columns:
      - name: Root SQL ID
        dataType: Long
        description: >-
          The root SQL ID for each triggered SQL
      - name: SQL ID
        dataType: Long
        description: >-
          The SQL ID for each triggered SQL(root SQL ID is the parent SQL ID)
      - name: SQL Description
        dataType: String
        description: >-
          The description of the SQL
      - name: SQL DF Duration
        dataType: Long
        description: >-
          The duration of the SQL
      - name: GPU Opportunity
        dataType: Long
        description: >-
          The expected duration of the SQL on GPU
  - label: execCSVReport
    description: >-
        Report containing the details of each executor in the SQL
    fileName: execs.csv
    scope: per-app
    columns:
      - name: SQL ID
        dataType: Long
        description: >-
          The associated SQL ID for the executor
      - name: Exec Name
        dataType: String
        description: >-
          The name of the executor
      - name: Expression Name
        dataType: String
        description: >-
          The name of the expression in the executor
      - name: Exec Duration
        dataType: Long
        description: >-
          The duration of the executor
      - name: SQL Node Id
        dataType: Long
        description: >-
          The Node ID of the associated SQL with the exec
      - name: Exec Is Supported
        dataType: Boolean
        description: >-
          Whether the executor is supported or not(true/false)
      - name: Exec Stages
        dataType: String
        description: >-
          The stages of the executor
      - name: Exec Children
        dataType: String
        description: >-
          The children of the executor
      - name: Exec Children Node Ids
        dataType: String
        description: >-
          The Node IDs of the children of the executor
      - name: Exec Should Remove
        dataType: Boolean
        description: >-
          Whether the executor should be removed or not(true/false)
      - name: Exec Should Ignore
        dataType: Boolean
        description: >-
          Whether the executor should be ignored or not(true/false)
      - name: Action
        dataType: String
        description: >-
          The action to be taken for the executor
  - label: unsupportedOpsCSVReport
    description: >-
      Report containing the details of each unsupported operator in the SQL
    fileName: unsupported_operators.csv
    scope: per-app
    columns:
      - name: SQL ID
        dataType: Long
        description: >-
          The associated SQL ID for the unsupported operator
      - name: Stage ID
        dataType: Long
        description: >-
          The associated stage ID for the unsupported operator
      - name: ExecId
        dataType: Long
        description: >-
          The associated executor ID for the unsupported operator
      - name: Unsupported Type
        dataType: String
        description: >-
          The type of the unsupported operator
      - name: Unsupported Operator
        dataType: String
        description: >-
          The details of the unsupported operator
      - name: Details
        dataType: String
        description: >-
          The details of the unsupported operator
      - name: Stage Duration
        dataType: Long
        description: >-
          The duration of the stage
      - name: App Duration
        dataType: Long
        description: >-
          The duration of the app
      - name: Action
        dataType: String
        description: >-
          The action to be taken for the unsupported operator
  - label: operatorsStatsCSVReport
    description: >-
      Report containing the details of each operator in the SQL
    fileName: operators_stats.csv
    scope: per-app
    columns:
      - name: SQL ID
        dataType: Long
        description: >-
          The associated SQL ID for the operator
      - name: Operator Type
        dataType: String
        description: >-
          The type of the operator
      - name: Operator Name
        dataType: String
        description: >-
          The name of the operator
      - name: Count
        dataType: Long
        description: >-
          The total count of the operator
      - name: Supported
        dataType: Boolean
        description: >-
          Whether the operator is supported or not(true/false)
      - name: Stages
        dataType: String
        description: >-
          Colon separated list of the stages of the operator
  - label: stagesCSVReport
    description: >-
      Report containing the details of each stage in the SQL
    fileName: stages.csv
    scope: per-app
    columns:
      - name: Stage ID
        dataType: Long
        description: >-
          The associated stage ID for the stage
      - name: Stage Task Duration
        dataType: Long
        description: >-
          Calculated as the total of all the task durations for that stage
      - name: Unsupported Task Duration
        dataType: Long
        description: >-
          Part of the stage task duration that is not supported
      - name: Stage Estimated
        dataType: Boolean
        description: >-
          Whether the stage runtime is estimated or not(true/false)
  - label: clusterInfoJSONReport
    description: >-
      Report containing the details of the cluster
    fileName: cluster_information.json
    fileFormat: JSON
    scope: per-app
    columns:
      - name: appName
        dataType: String
        description: >-
          The name of the app for the associated event log
      - name: appId
        dataType: String
        description: >-
          The ID of the app for the associated event log
      - name: eventLogPath
        dataType: String
        description: >-
          The path of the event log for the associated app
      - name: sourceClusterInfo
        dataType: Dict
        description: >-
          The source cluster information for the associated app(dictionary containing the cluster information)
      - name: recommendedClusterInfo
        dataType: Dict
        description: >-
          The recommended cluster information for the associated app(dictionary containing the cluster information)
  # the following table is databricks specific table
  - label: clusterTagsCSVReport
    description: >-
      Report containing the details of the cluster tags
    fileName: clusters_tags.csv
    scope: per-app
    columns:
      - name: Property Name
        dataType: String
        description: >-
          The name of the property
      - name: Property Value
        dataType: String
        description: >-
          The value of the property
  # the following table is enabled only when ml-functions argument is added to the arguments.
  - label: mlFunctionsCSVReport
    description: >-
      Report containing the details of the ML functions
    fileName: ml_functions.csv
    scope: per-app
    columns:
      - name: Stage ID
        dataType: Long
        description: >-
          The stage IDs of the ML functions
      - name: ML Functions
        dataType: String
        description: >-
          The ML functions in the stage
      - name: Stage WallClock Duration (ms)
        dataType: Long
        description: >-
          Calculated as (submissionTime - completionTime) of the given stage
  # the following table is enabled only when ml-functions argument is added to the arguments.
  - label: mlFunctionsDurationsCSVReport
    description: >-
      Report containing the details of the ML functions durations
    fileName: ml_functions_durations.csv
    scope: per-app
    columns:
      - name: Stage Ids
        dataType: String
        description: >-
          The stage IDs of the ML functions
      - name: ML Function Name
        dataType: String
        description: >-
          The ML functions name in the stage
      - name: Total Duration
        dataType: Long
        description: >-
          The total duration of the ML functions
