Recommendations cannot be generated.
    Reason: The cluster information was not set.
    To enable recommendation, the cluster properties must be defined.
    Please make sure to set the arguments properly by either:
        1. Setting <{{ CLUSTER_ARG }}> argument and optional set <eventlogs> if
            the path is not defined by the cluster properties; or
        2. Setting both <{{ CLUSTER_ARG }}> and <eventlogs>
