/*
 * Copyright (c) 2025, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.rapids.tool.plangraph

import scala.collection.mutable

/**
 * Base class for platform-aware SparkPlanGraphNode. Non spark platforms should extend this class.
 *
 * @param id generated by "SparkPlanGraph". There is no duplicate id in a graph
 * @param actualName the actual name of this platform's SparkPlan node
 * @param actualDesc the actual description of this platform's SparkPlan node
 * @param sparkName the name of this SparkPlan node
 * @param sparkDesc the description of this SparkPlan node
 * @param metrics metrics that this SparkPlan node will track
 */
class PWPlanGraphNode(
    id: Long,
    actualName: String,
    actualDesc: String,
    sparkName: String,
    sparkDesc: String,
    metrics: collection.Seq[SQLPlanMetric]
) extends SparkPlanGraphNode(id, sparkName, sparkDesc, metrics) {
  /**
   * The actual name that belongs to the platform's entity. For example, in Photon plans,
   * this would be the Photon-specific operator name. For spark, it would return the same operator
   * name.
   *
   * @return A string identifier for the platform's entity.
   */
  override def platformName: String = actualName

  /**
   * A human-readable description of the platform's entity. Same as the platformName, it represents
   * the true name as per the platform's terminology. Oter wise, it should provide the same details
   * as Spark OSS. i.e., simpleString for planInfo, and nodeDesc for planGraphNode.
   *
   * @return A string representing the description of the platform's entity.
   */
  override def platformDesc: String = actualDesc

  override def isOssSparkNode: Boolean = false
}

/**
 * Base class for platform-aware SparkPlanGraphCluster. Non spark platforms should extend this
 * class.
 *
 * @param id generated by "SparkPlanGraph". There is no duplicate id in a graph
 * @param actualName the actual name of this platform's SparkPlan node
 * @param actualDesc the actual description of this platform's SparkPlan node
 * @param sparkName the name of this SparkPlan node
 * @param sparkDesc the description of this SparkPlan node
 * @param nodes child nodes of this cluster
 * @param metrics metrics that this SparkPlan node will track
 */
class PWPlanGraphCluster(
    id: Long,
    actualName: String,
    actualDesc: String,
    sparkName: String,
    sparkDesc: String,
    nodes: mutable.ArrayBuffer[SparkPlanGraphNode],
    metrics: collection.Seq[SQLPlanMetric]
) extends SparkPlanGraphCluster(id, sparkName, sparkDesc, nodes, metrics) {
  /**
   * The actual name that belongs to the platform's entity. For example, in Photon plans,
   * this would be the Photon-specific operator name. For spark, it would return the same operator
   * name.
   *
   * @return A string identifier for the platform's entity.
   */
  override def platformName: String = actualName

  /**
   * A human-readable description of the platform's entity. Same as the platformName, it represents
   * the true name as per the platform's terminology. Oter wise, it should provide the same details
   * as Spark OSS. i.e., simpleString for planInfo, and nodeDesc for planGraphNode.
   *
   * @return A string representing the description of the platform's entity.
   */
  override def platformDesc: String = actualDesc

  override def isOssSparkNode: Boolean = false
}
